export const courseNameToCode = {
  "Kỹ năng học tập": "PDP102",
  "Tin học": "COM107",
  "Nhập môn lập trình": "COM108",
  "Nhập môn Công nghệ thông tin": "ITI101",
  "Tiếng Anh 1.1": "ENT112",
  "Giáo dục thể chất - Vovinam": "VIE103",
  "Xây dựng trang Web": "WEB101",
  "Lập trình PHP cơ bản": "WEB108",
  "Cơ sở dữ liệu": "COM201",
  "Lập trình cơ sở với JavaScript": "WEB104",
  "Tiếng Anh 1.2": "ENT122",
  "Chính trị": "VIE101",
  "Thiết kế Web với HTML5&CSS3": "WEB302",
  "Lập trình PHP 1": "WEB201",
  "Quản trị website": "WEB102",
  "Dự án mẫu": "WEB204",
  "Tiếng Anh 2.1": "ENT212",
  "Kỹ năng phát triển cá nhân": "PDP103",
  "Thiết kế UI/UX": "WEB105",
  "Marketing trên Internet": "WEB205",
  "Lập trình JavaScript nâng cao": "WEB206",
  "Dự án 1": "PRO101",
  "Front-End Frameworks": "WEB207",
  "Lập trình ECMAScript": "WEB501",
  "Tiếng Anh 2.2": "ENT222",
  "Lập trình PHP 2": "WEB301",
  "NodeJS & Restful Web Service": "WEB503",
  "Xây dựng trang Web 2": "WEB203",
  "Lập trình TypeScript": "WEB502",
  "Kỹ năng làm việc": "PDP104",
  "Quản lý dự án với Agile": "PMA101",
  "Lập trình Front-End Framework 1": "WEB208",
  "Lập trình PHP 3": "WEB401",
  "Lập trình Front-End Framework 2": "WEB209",
  "Khởi sự doanh nghiệp": "SYB301",
  "Thực tập tốt nghiệp": "PRO116",
  "Dự án tốt nghiệp": "PRO220",
  "Pháp luật": "VIE102",
  "Giáo dục quốc phòng": "VIE104"
};